/**
 * src/builder/init-mesh.js
 *
 * Create the mesh substrate in a given mesh root directory.
 *
 * Structure created:
 *   <meshRoot>/mesh.json                                  — manifest
 *   <meshRoot>/mesh/skills/citation-format/SKILL.md      — seed skill
 *   <meshRoot>/mesh/mcp.json                              — global tool registry (declared only)
 *   <meshRoot>/README.md                                  — orientation
 *
 * Refuses (throws) if mesh.json already exists.
 * Returns the list of absolute paths created.
 */

import { access, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { writeManifest } from './manifest.js';

const SEED_SKILL_CONTENT = `---
name: citation-format
description: Format references consistently across agents.
---

When producing citations, use the following format:
[Author, Year] Title. Source. URL (if available).
Apply this format to all reference lists generated by any agent in this mesh.
`;

const README_CONTENT = `# Agent Mesh

This directory is an **agent-mesh root** managed by the \`agent-mesh\` tool.

- \`mesh.json\` is the **manifest** — the authoring source of truth for membership,
  topology (who may call whom), and mode policy. Edit it to add agents or change wiring.
- \`mesh/skills/\` holds **shared skills** inherited as trusted prompt configuration
  by member agents (ceiling-bounded via \`AGENT_MESH_MESH_ROOT\`).
- \`mesh/mcp.json\` is a **shared tool registry**: servers marked
  \`"x-agentmesh": { "readOnly": true }\` are grantable to member agents under the
  same rule as a folder's own \`.mcp.json\` (declaration ≠ grant; \`do\` still
  grants none). Unmarked entries remain discovery-only.

To see an overview of this mesh and its agents, run:

    agent-mesh dashboard .
`;

/**
 * Create the mesh substrate.
 *
 * @param {string} meshRoot  absolute path to the mesh root directory
 * @returns {Promise<string[]>}  list of absolute paths created
 */
export async function initMesh(meshRoot) {
  // Refuse if mesh.json already exists
  const meshJsonPath = join(meshRoot, 'mesh.json');
  try {
    await access(meshJsonPath);
    // If we reach here the file exists
    throw new Error(`mesh.json already exists at ${meshJsonPath} — refusing to overwrite an existing mesh`);
  } catch (err) {
    if (err.code !== 'ENOENT') {
      // Re-throw our own error or other unexpected errors
      throw err;
    }
    // ENOENT means the file does not exist — proceed
  }

  const created = [];

  // 1. Write mesh.json
  const initialManifest = {
    meshVersion: '0.1.0',
    defaults: { transport: 'stdio' },
    agents: []
  };
  await writeManifest(meshRoot, initialManifest);
  created.push(meshJsonPath);

  // 2. Create mesh/skills/citation-format/SKILL.md
  const skillDir = join(meshRoot, 'mesh', 'skills', 'citation-format');
  await mkdir(skillDir, { recursive: true });
  const skillPath = join(skillDir, 'SKILL.md');
  await writeFile(skillPath, SEED_SKILL_CONTENT, 'utf8');
  created.push(skillPath);

  // 3. Create mesh/mcp.json
  const mcpPath = join(meshRoot, 'mesh', 'mcp.json');
  await writeFile(mcpPath, JSON.stringify({ mcpServers: {} }, null, 2) + '\n', 'utf8');
  created.push(mcpPath);

  // 4. Create README.md
  const readmePath = join(meshRoot, 'README.md');
  await writeFile(readmePath, README_CONTENT, 'utf8');
  created.push(readmePath);

  return created;
}
