#!/usr/bin/env bash
# mac-bridge-setup.sh — reproduce the MAC half of the cross-machine A2A bridge.
#
# What it builds (idempotent — safe to re-run):
#   1. ~/.agent-mesh/bridge/serve-agents.sh   serves N dev-mesh agents over serve-a2a-http,
#                                             each sourcing the headless-claude token, self-restarting.
#   2. ~/.agent-mesh/bridge/tunnel.sh         a Mac-initiated reverse SSH tunnel (ssh -R) that
#                                             publishes each agent's loopback port on the box.
#   3. two launchd jobs (KeepAlive) that keep both alive across logout/reboot/disconnect.
#
# WHY a Mac-initiated reverse tunnel: the box (Windows+WSL) cannot dial in to the Mac
# (firewall blocks inbound; userspace Tailscale doesn't route inbound), but Mac->box SSH works.
# `ssh -R BOXPORT:127.0.0.1:MACPORT` binds the listener on the box's loopback, which WSL shares
# via mirrored networking — so the WSL concierge reaches the Mac agent at 127.0.0.1:BOXPORT.
#
# The box half is set up by box-bridge-setup.sh (run on the box). See README.md.
#
# Config via env (defaults match the live deployment):
#   BRIDGE_DIR   ~/.agent-mesh/bridge            where the generated scripts + token live
#   DEPLOY_DIR   ~/.agent-mesh/deploy            checkout holding bin/agent-mesh.js + dev-mesh/
#   MESH_DIR     $DEPLOY_DIR/dev-mesh            the mesh root (has mesh.json)
#   NODE         $(command -v node)              node binary launchd will use
#   BOX_SSH      enoch-lan                       ssh host alias for the box
#   TOKEN_FILE   $BRIDGE_DIR/.claude-token       file exporting CLAUDE_CODE_OAUTH_TOKEN
#   AGENTS       "coder:8790 tester:8792 analyst:8794"   name:MACPORT list to serve+forward
#   PORT_STRIDE  1                               BOXPORT = MACPORT + PORT_STRIDE
#   LABEL_PREFIX com.danabaxia.agent-mesh        launchd label prefix
set -euo pipefail

BRIDGE_DIR="${BRIDGE_DIR:-$HOME/.agent-mesh/bridge}"
DEPLOY_DIR="${DEPLOY_DIR:-$HOME/.agent-mesh/deploy}"
MESH_DIR="${MESH_DIR:-$DEPLOY_DIR/dev-mesh}"
NODE="${NODE:-$(command -v node || true)}"
BOX_SSH="${BOX_SSH:-enoch-lan}"
TOKEN_FILE="${TOKEN_FILE:-$BRIDGE_DIR/.claude-token}"
AGENTS="${AGENTS:-coder:8790 tester:8792 analyst:8794}"
PORT_STRIDE="${PORT_STRIDE:-1}"
LABEL_PREFIX="${LABEL_PREFIX:-com.danabaxia.agent-mesh}"

AGENT_MESH_JS="$DEPLOY_DIR/bin/agent-mesh.js"
LAUNCH_DIR="$HOME/Library/LaunchAgents"

die() { echo "ERROR: $*" >&2; exit 1; }

[ -n "$NODE" ]                || die "node not found on PATH; set NODE=/path/to/node"
[ -f "$AGENT_MESH_JS" ]       || die "agent-mesh.js not at $AGENT_MESH_JS; set DEPLOY_DIR to your checkout"
[ -d "$MESH_DIR" ]            || die "mesh dir not at $MESH_DIR; set MESH_DIR"
command -v ssh >/dev/null     || die "ssh not found"

mkdir -p "$BRIDGE_DIR" "$LAUNCH_DIR"

# --- token file (the operator pastes the headless-claude token here once) -----------------
if [ ! -f "$TOKEN_FILE" ]; then
  cat > "$TOKEN_FILE" <<'EOF'
# Headless-claude auth for bridged agents. Without this, a detached/launchd
# `claude -p` is "Not logged in" — interactive auth does not survive a detached spawn.
# Get the token in a REAL terminal (it's an interactive TUI; do NOT background it):
#     claude setup-token
# then paste the sk-ant-oat... value below (uncomment the line).
# export CLAUDE_CODE_OAUTH_TOKEN=sk-ant-oat01-...
EOF
  chmod 600 "$TOKEN_FILE"
  echo "WROTE  $TOKEN_FILE (placeholder — paste your token, see comments)"
else
  chmod 600 "$TOKEN_FILE"
  echo "KEEP   $TOKEN_FILE (already present; not overwriting your token)"
fi

# --- serve-agents.sh: serve each agent over serve-a2a-http, self-restart -------------------
SERVE_SH="$BRIDGE_DIR/serve-agents.sh"
{
  echo '#!/usr/bin/env bash'
  echo '# GENERATED by mac-bridge-setup.sh — serves the bridged dev-mesh agents. Re-run setup to regenerate.'
  echo 'set -uo pipefail'
  echo "source \"$TOKEN_FILE\" 2>/dev/null || true"
  echo 'pids=()'
  echo 'cleanup() { for p in "${pids[@]:-}"; do kill "$p" 2>/dev/null || true; done; }'
  echo 'trap cleanup EXIT INT TERM'
  for pair in $AGENTS; do
    name="${pair%%:*}"; mport="${pair##*:}"
    echo ""
    echo "# --- $name on 127.0.0.1:$mport ---"
    echo "( while true; do \\"
    echo "    \"$NODE\" \"$AGENT_MESH_JS\" serve-a2a-http \"$MESH_DIR/$name\" --port $mport --host 127.0.0.1; \\"
    echo "    echo \"[serve-agents] $name exited (\$?), restarting in 2s\" >&2; sleep 2; \\"
    echo "  done ) & pids+=(\$!)"
  done
  echo ""
  echo 'wait'
} > "$SERVE_SH"
chmod +x "$SERVE_SH"
echo "WROTE  $SERVE_SH"

# --- tunnel.sh: one reverse SSH tunnel publishing every agent port on the box --------------
TUNNEL_SH="$BRIDGE_DIR/tunnel.sh"
{
  echo '#!/usr/bin/env bash'
  echo '# GENERATED by mac-bridge-setup.sh — reverse SSH tunnel (Mac -> box). Re-run setup to regenerate.'
  echo 'set -uo pipefail'
  echo 'exec ssh -N \'
  echo '  -o ServerAliveInterval=30 -o ServerAliveCountMax=3 \'
  echo '  -o ExitOnForwardFailure=yes -o BatchMode=yes \'
  for pair in $AGENTS; do
    mport="${pair##*:}"; bport=$(( mport + PORT_STRIDE ))
    echo "  -R ${bport}:127.0.0.1:${mport} \\"
  done
  echo "  \"$BOX_SSH\""
} > "$TUNNEL_SH"
chmod +x "$TUNNEL_SH"
echo "WROTE  $TUNNEL_SH"

# --- launchd plists -----------------------------------------------------------------------
write_plist() {  # label  program-path
  local label="$1" prog="$2" plist="$LAUNCH_DIR/$1.plist"
  cat > "$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key>
  <array><string>/bin/bash</string><string>$prog</string></array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>$(dirname "$NODE"):/usr/bin:/bin:/usr/sbin:/sbin</string>
    <key>HOME</key><string>$HOME</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$BRIDGE_DIR/$label.log</string>
  <key>StandardErrorPath</key><string>$BRIDGE_DIR/$label.log</string>
</dict>
</plist>
EOF
  launchctl unload "$plist" 2>/dev/null || true
  launchctl load "$plist"
  echo "LOADED $label  (log: $BRIDGE_DIR/$label.log)"
}

write_plist "$LABEL_PREFIX.bridge-agents" "$SERVE_SH"
write_plist "$LABEL_PREFIX.bridge-tunnel" "$TUNNEL_SH"

echo ""
echo "=== Mac bridge ready ==="
echo "Agents served + reverse-tunneled to $BOX_SSH:"
for pair in $AGENTS; do
  name="${pair%%:*}"; mport="${pair##*:}"; bport=$(( mport + PORT_STRIDE ))
  echo "  $name : Mac 127.0.0.1:$mport  ->  box 127.0.0.1:$bport"
done
echo ""
echo "Next:"
echo "  1. If $TOKEN_FILE is still a placeholder, run 'claude setup-token' in a real"
echo "     terminal and paste the token (then: launchctl kickstart -k gui/\$UID/$LABEL_PREFIX.bridge-agents)."
echo "  2. On the box, run box-bridge-setup.sh with matching ports (see scripts/bridge/README.md)."
echo "  3. Verify from the box:  curl -s -X POST http://127.0.0.1:<BOXPORT>/rpc \\"
echo "       -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"ping\"}'   ->  {\"result\":{}}"
