// src/mesh-improvement/issues.js — pure: gated MIR → GitHub issue action-plan.
// Dedup is by ledger[id].issueNumber ONLY — never by reading issue bodies.
import { MIR_ID_RE } from '../config.js';

const marker = (id) => `<!-- mesh-scan:${id} -->`;

function assertId(id) {
  if (!MIR_ID_RE.test(id)) throw new Error(`invalid finding id: ${JSON.stringify(id)}`);
}
function tierLabel(f) {
  if (f.tier === 'hard') return f.cluster === 'security-invariant' ? 'security' : 'regression';
  return f.cluster === 'behavior-regression' ? 'behavior' : 'perf';
}
// The label that decides routing (routeFor). A HARD regression — a test/eval that was
// green and is now red — is a DEFECT, so it gets `bug`: issue-sweep then auto-routes it
// to the Coder (bug-autofix, do-mode, no human approval). This is the automatic
// report → Coder handoff. Security-invariant breaks and soft improvement findings stay
// `idea` (human-gated) — those need a human's judgment before any code change.
function routingLabel(f) {
  return (f.tier === 'hard' && f.cluster !== 'security-invariant') ? 'bug' : 'idea';
}
function title(f) {
  const m = f.metric;
  if (f.tier === 'hard') return `[mesh-scan] ${f.cluster}: ${f.id}`;
  return `[mesh-scan] ${f.cluster}: ${m.name} regressed (${m.deltaPct}%)`;
}
function body(f, mir) {
  const m = f.metric;
  return [
    marker(f.id),
    `**Finding** \`${f.id}\` (${f.severity})`, '',
    f.tier === 'soft'
      ? `- metric: \`${m.name}\` = ${m.value} (baseline ${m.baseline}, Δ ${m.deltaPct}%)`
      : `- hard signal: ${f.evidence?.trace ?? f.cluster}`,
    f.weakestCell ? `- weakest cell: ${f.weakestCell.peers}× ${f.weakestCell.overlap}` : null,
    f.evidence?.logPath ? `- log: \`${f.evidence.logPath}\`` : null,
    f.evidence?.scorecardPath ? `- scorecard: \`${f.evidence.scorecardPath}\`` : null,
    '', `_Generated by the Mesh Improvement Report at ${mir.at}._`,
  ].filter((x) => x != null).join('\n');
}

export function planIssues(mir, { recoverRuns, scanLabel }) {
  const plan = [];
  const fileable = mir.findings.filter((f) => f.fileable);
  const fileableIds = new Set(fileable.map((f) => f.id));

  for (const f of fileable) {
    assertId(f.id);
    const issueNumber = mir.ledger?.[f.id]?.issueNumber ?? null;
    plan.push({
      id: f.id, issueNumber, action: issueNumber == null ? 'create' : 'update',
      title: title(f), body: body(f, mir),
      labels: [routingLabel(f), scanLabel, tierLabel(f)], marker: marker(f.id),
    });
  }
  // Close issues whose finding has been clean for >= recoverRuns and is not fileable now.
  for (const [id, entry] of Object.entries(mir.ledger ?? {})) {
    if (fileableIds.has(id)) continue;
    if (entry.issueNumber != null && (entry.cleanRuns ?? 0) >= recoverRuns) {
      assertId(id);
      plan.push({
        id, issueNumber: entry.issueNumber, action: 'close',
        title: null, labels: [], marker: marker(id),
        body: `${marker(id)}\nResolved: clean for ${entry.cleanRuns} consecutive runs as of ${mir.at}.`,
      });
    }
  }
  return plan;
}
